### ISSUE TITLE
Persistir cadastro incompleto em sessão

### ISSUE THREAD

**Issue by leomp12** [ecomclub/storefront-app#103]
Quando o cliente inicia o cadastro com e-mail no checkout mas não finaliza a compra o usuário não é salvo na API do Passport, e isto vai continuar assim por enquanto, mas podemos persistir os dados em `sessionStorage` (por segurança `localStorage` não) e preencher automaticamente se ele voltar ao checkout durante a mesma sessão.

O fluxo é:
1. Acessar o checkout sem login;
2. Inserir um e-mail sem cadastro;
3. Preencher o formulário de cadastro e prosseguir para o checkout;
4. Voltar para a home sem finalizar a compra;
5. Voltar para o checkout;

Neste ponto o cadastro terá que ser refeito, utilizando `sessionStorage` podemos evitar isto e pular direto para o checkout.

**Comment by igorsfreitas** [comment]
Já inseri o sessionStorage no componente, to meio travado só em como colocar o valor default nesses cleaves componentes que é o input de Phone e Data.

**Comment by leomp12** [comment]
https://github.com/ecomclub/storefront-app/pull/114
