### ISSUE TITLE
Account component/view

### ISSUE THREAD

**Issue by leomp12** [ecomclub/storefront-app#26]
- Create `src/components/EcAccount.vue` with same approach of other components;
  - Never use vuex directly (receive props, support `.sync`);
  - It should import `EcIdentify`, `EcAddresses` and `EcAccountForm`;
  - Must show identification form if user not logged;
  - If logged, show [tabs](https://bootstrap-vue.js.org/docs/components/tabs/#tabs) on header;
    - Default tab for account form;
    - Tab for addresses list;
    - Tab for orders list (_TODO_);
- Setup `src/views/Account.vue` route with same approach of the other routes;

**Comment by leomp12** [comment]
@talissonf conseguimos fechar isto esta semana?

**Comment by talissonf** [comment]
@leomp12 Sim!
