### ISSUE TITLE
Enviar para passport no primeiro acesso na página de confirmação

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/storefront-app#82]

**Comment by matheusgnreis** [comment]
Usando email primeira vez para compra não está sendo registrado na conta do cliente tanto nascimento, quanto data de nascimento, pois não está sendo feito o patch, após essa inserção de dados em primero acesso na loja. Nos demais acessos funciona

**Comment by leomp12** [comment]
@thiagoabreudev como estamos com isso aqui?

Eu preciso atualizar os widgets no [`storefront-template`](https://github.com/ecomclub/storefront-template), mas tenho que atualizar todos no mesmo release porque fiz umas correções do peer dependencies.

Só que fico travado enquanto o `storefront-app` estiver usando o passport client v1, porque a versão atualizada do [`widget-user`](https://github.com/ecomclub/widget-user) já está na v2, aí misturando os dois se o cliente logar na loja não estará logado no checkout, e vice-versa...
